UniversityNotifications/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from user_profile.urls import router

urlpatterns = [
	path('admin/', admin.site.urls),
	path('', include('user_profile.urls')),
]

user_profile/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from rest_framework.authtoken import views as rest_view
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView
from rest_framework import routers

from . import views

app_name="user_profile"

router = routers.DefaultRouter()
  
# define the router path and viewset to be used
router.register(r'api/userprofile', views.UserProfileViewSet)
router.register(r'api/user', views.UserViewSet)


urlpatterns = [
	path('', views.index, name='dashboard'),
	path('course/delete/<int:pk>', views.delete_course, name='delete_course'),
	path('course/<int:pk>', views.course_details, name='course_details'),
	path('course/', views.courses, name='courses'),
	path('subject/<int:pk>', views.delete_subject, name='delete_subject'),
	path('subject/', views.subjects, name='subjects'),
	path('course/apply/', views.course_apply, name='course_apply'),
	path('students/', views.students, name='students'),
	path('course/students/<int:pk>/', views.course_students, name='course_students'),
	#path('password/change', auth_views.PasswordChangeView.as_view(success_url='/signin/'), name='change_password'),
	path('password/change/', views.change_password, name='change_password'),
	path('password/reset/', views.reset_password, name='password_reset'),

	#path('password/reset/', auth_views.PasswordResetView.as_view(email_template_name='user_profile/password_reset_email.html', success_url='/password/reset/done/'), name='password_reset'),
	path('password/reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
	path('password/reset/done/', views.reset_password_done, name='reset_password_done'),
	#path('password/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url='/password/reset/complete'), name='password_reset_confirm'),
	path('password/reset/<token>/', views.reset_password_confirm, name='reset_password_confirm'),


	path('signup/', views.sign_up, name='sign_up'),
	path('signin/', views.sign_in, name='sign_in'),
	path('signout/', views.sign_out, name='sign_out'),
	path('api/', views.api_view, name='api_view'),

	path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    
	path('api-token-auth/', rest_view.obtain_auth_token),

	path('api/teachers/', views.TeacherList.as_view() , name='teacher-list' ),
	path('api/students/', views.student_list , name='student-list' ),
	path('', include(router.urls)),

	path('stu/', views.stu, name='stu')

]

user_profile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token

@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)
        print("token_create!!!")

# Create your models here.

class UserProfile(models.Model):
	USER_TYPE = [
    ('student', 'Student'),
    ('teacher', 'Teacher'),
	]
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	phone_number = models.CharField(max_length=10, null=True)
	dob = models.DateField(null=True)
	address = models.CharField(max_length=100, null=True)
	user_type = models.CharField(max_length=10, choices=USER_TYPE)

	def __str__(self):
		return self.user.username

class Course(models.Model):
	QUALIFICATIONS = [
	('higher_secondary', 'Higher Secondary'),
	('graduate', 'Graduate'),
	('post_graduate', 'Post Graduate'),
	]
	name = models.CharField(max_length=50)
	duration = models.IntegerField()
	pre_requisite = models.CharField(max_length=20, choices=QUALIFICATIONS)
	is_vocational = models.BooleanField(default=False)
	subjects = models.ManyToManyField('Subject')

	def __str__(self):
		return self.name

class Subject(models.Model):
	name = models.CharField(max_length=30)
	teacher = models.ForeignKey('Teacher', on_delete=models.CASCADE)

	def __str__(self):
		return self.name


class Student(models.Model):
	QUALIFICATIONS = [
	('higher_secondary', 'Higher Secondary'),
	('graduate', 'Graduate'),
	('post_graduate', 'Post Graduate'),
	]
	user_profile = models.OneToOneField(UserProfile, on_delete=models.CASCADE)
	qualification = models.CharField(max_length=20, choices=QUALIFICATIONS)
	courses = models.ManyToManyField(Course, null=True, blank=True)
	start_year = models.CharField(max_length=4, null=True, blank=True)

	def __str__(self):
		return self.user_profile.user.username


class Teacher(models.Model):
	user_profile = models.OneToOneField(UserProfile, on_delete=models.CASCADE)

	def __str__(self):
		return self.user_profile.user.username

user_profile/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.forms import formset_factory
from django.contrib import messages
from django.db.models import Q
from django.db.models.functions import Coalesce
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes, force_str
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, JsonResponse

from rest_framework.authtoken.models import Token
from rest_framework.decorators import api_view
from rest_framework import viewsets
from rest_framework import generics, authentication, permissions 
from rest_framework.response import Response
from rest_framework.reverse import reverse as res
from rest_framework.renderers import TemplateHTMLRenderer, AdminRenderer

from .serializers import *
from .decorators import *
from .models import *
from .forms import *

@api_view(['GET'])
def student_list(request):
	if request.method == 'GET':
		students = Student.objects.all()
		serializer = StudentSerializer(students, many=True)
		return JsonResponse(serializer.data, safe=False)


class TeacherList(generics.ListAPIView):
	queryset = Teacher.objects.all()
	serializer_class = TeacherSerializer
	renderer_classes = [TemplateHTMLRenderer]
	# authentication_classes = [authentication.TokenAuthentication]
	# permission_classes = [permissions.IsAuthenticated]

	def get(self, request, *args, **kwargs):
		self.queryset = self.get_queryset()
		return Response({'teachers': self.queryset}, template_name='user_profile/teacher_api.html')

class UserProfileViewSet(viewsets.ModelViewSet):
	queryset = UserProfile.objects.all()
	serializer_class = UserProfileSerializer
	renderer_classes = [AdminRenderer]

class UserViewSet(viewsets.ModelViewSet):
	queryset = User.objects.all()
	serializer_class = UserSerializer
	renderer_classes = [AdminRenderer]

# class UserProfileList(generics.ListAPIView):
# 	queryset = UserProfile.objects.all()
# 	serializer_class = UserProfileSerializer
# 	# authentication_classes = [authentication.TokenAuthentication]
# 	# permission_classes = [permissions.IsAuthenticated]

# class UserProfileDetail(generics.RetrieveAPIView):
# 	queryset = UserProfile.objects.all()
# 	serializer_class = UserProfileSerializer


@api_view(['GET'])
def stu(request):
	students = Student.objects.all()
	serializer = StudentSerializer(students, many=True)
	print(serializer)
	return Response({"students": serializer.data}, template_name='user_profile/student_api.html')


def sign_up(request):
	if request.method == "POST":
		form = UserSignUpForm(request.POST)
		if form.is_valid():
			clean_data = form.cleaned_data
			first_name = clean_data['first_name'].lower()
			last_name = clean_data['last_name'].lower()
			email = clean_data['email']
			username = clean_data['username']
			password = clean_data['password']
			user_type = clean_data['user_type']
			
			user = User.objects.create_user(username, email, password, first_name=first_name, last_name=last_name)
			UserProfile.objects.create(user=user, user_type=user_type)

			messages.success(request, 'User Created Successfully!!!')
			return redirect(reverse('user_profile:sign_in'))
	else:
		form = UserSignUpForm()
	return render(request, 'user_profile/sign_up.html', {'form': form })

def sign_in(request):
	if request.user.is_authenticated:
		return redirect(reverse('user_profile:dashboard'))

	if request.method == "POST":
		form = UserSignInForm(request.POST)
		if form.is_valid():
			clean_data = form.cleaned_data
			username = clean_data['username']
			password = clean_data['password']
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				return redirect(reverse('user_profile:dashboard'))
	else:
		form = UserSignInForm()
	return render(request, 'user_profile/sign_in.html', {'form': form})

def sign_out(request):
	logout(request)
	return redirect(reverse("user_profile:sign_in"))

@login_required(login_url='/signin')
def index(request):
	user_profile = request.user.userprofile
	initial = {
		'first_name': user_profile.user.first_name.title(),
		'last_name': user_profile.user.last_name.title(),
		'username': user_profile.user.username,
		'email': user_profile.user.email,
		'user_type': user_profile.user_type,
		'phone_number': user_profile.phone_number,
		'dob': user_profile.dob,
		'address': user_profile.address,
		}
	context = {}

	if request.method == "POST":
		if 'user_profile' in request.POST:
			form = UserProfileForm(request.POST, initial=initial, prefix='user_profile')
			context['form'] = form
			if form.is_valid() and form.has_changed():
				print("Changing form")
				clean_data = form.cleaned_data
				phone_number = clean_data['phone_number']
				dob = clean_data['dob']
				address = clean_data['address']

				UserProfile.objects.filter(user=request.user).update(phone_number=phone_number, dob=dob, address=address)
				messages.success(request, 'Profile updated successfully!!!')
				return redirect(reverse('user_profile:dashboard'))

		elif 'student' in request.POST:
			student = Student.objects.filter(user_profile__user__username=request.user.username)
			if student.exists():
				studentform = AddStudentForm(request.POST ,initial={'qualification':request.user.userprofile.student.qualification}, prefix='student')
				context['studentform'] = studentform
			else:
				studentform = AddStudentForm(request.POST, prefix='student')
				context['studentform'] = studentform
			if studentform.is_valid() and studentform.has_changed():
				qualification = studentform.cleaned_data.get('qualification')
				student = Student.objects.get_or_create(user_profile=request.user.userprofile)
				student[0].qualification = qualification
				student[0].save()
				messages.success(request, 'Profile updated successfully!!!')
				return redirect(reverse('user_profile:dashboard'))
	else:
		context['form'] = UserProfileForm(initial=initial, prefix='user_profile')
	if request.user.userprofile.user_type == 'student':
		student = Student.objects.filter(user_profile=request.user.userprofile)
		if student.exists():
			context['studentform'] = AddStudentForm(initial={'qualification':request.user.userprofile.student.qualification}, prefix='student')
		else:
			context['studentform'] = AddStudentForm(prefix='student')
	return render(request, 'user_profile/dashboard.html', context)

@login_required(login_url='/signin/')
def courses(request):
	if request.method == "POST":
		form = AddCourseForm(request.POST)
		if form.is_valid():
			form.save()
			messages.success(request, 'Course added successfully!!!')
			return redirect(reverse('user_profile:courses'))
	
	else:
		courses = Course.objects.all()
		context = {'courses': courses}
		user_profile = request.user.userprofile
		if user_profile.user_type != "teacher":
			message = "You don't have previledge to add course."
			return render(request, 'user_profile/courses.html', {'message': message})
		
		else:
			form = AddCourseForm()
		context['form'] = form
		return render(request, 'user_profile/courses.html', context)

@login_required(login_url='/signin/')
def course_details(request, pk):
	course = Course.objects.get(pk=pk)
	return render(request, 'user_profile/course_details.html', {'course': course})


@login_required(login_url='/signin/')
@check_allowed_user_role('student')
def course_apply(request):
	if request.user.userprofile.user_type == "teacher":
		return redirect(reverse('user_profile:dashboard'))
	initial = {
		"start_year": request.user.userprofile.student.start_year
	}
	if request.method == "POST":
		form = CourseApplyForm(request.POST, initial=initial, **{"user_profile": request.user.userprofile})
		if form.is_valid():
			clean_data = form.cleaned_data
			start_year = clean_data['start_year']
			course = clean_data['course']
			student = Student.objects.get_or_create(user_profile=request.user.userprofile)[0]
			student.start_year = start_year
			student.courses.add(course)
			messages.success(request, 'Applied for course successfully!!!')
			return redirect(reverse('user_profile:dashboard'))
	else:
		form = CourseApplyForm(initial=initial, **{"user_profile": request.user.userprofile})
	courses = request.user.userprofile.student.courses.values()
	return render(request, 'user_profile/course_apply.html', {"form": form, 'courses': courses})

@login_required(login_url='/signin/')
def course_students(request, pk):
	form = SearchForm(request.GET)
	search_string = request.GET.get('name', '')
	sort_by = request.GET.get('sort_by', 'asc_name')
	first_name = Q(user_profile__user__first_name__icontains= search_string)
	last_name = Q(user_profile__user__last_name__icontains= search_string)
	students = Student.objects.filter(courses__id=pk).filter( first_name | last_name )

	if sort_by =='desc_year':
		students = students.order_by('-start_year')
	elif sort_by == 'asc_year':
		students = students.order_by('start_year')
	elif sort_by == 'desc_name':
		students = students.order_by(Coalesce('user_profile__user__first_name', 'user_profile__user__last_name').desc())
	else:
		students = students.order_by(Coalesce('user_profile__user__first_name', 'user_profile__user__last_name').asc())
	return render(request, 'user_profile/students.html', {'form':form, 'students': students, 'course_id':pk})


@login_required(login_url='/signin/')
@check_allowed_user_role(role='teacher')
def students(request):
	if request.method == 'GET':
		form = SearchForm(request.GET)
		search_string = request.GET.get('name', '')
		sort_by = request.GET.get('sort_by', 'asc_name')

user_profile/templates/user_profile/course_apply.html
{% extends 'user_profile/navbar.html' %}

{% block title %}
	Courses
{% endblock %}

{% block content %}

	{% if messages %}
		<ul class="messages">
	    	{% for message in messages %}
	    		<li {% if message.tags %} class="{{ message.tags }}"{% endif %}>
	    			{{ message }}
	    		</li>
	 	   {% endfor %}
		</ul>
	{% endif %}
	<div class="m-3">
		{% if courses %}
			<h5>
				Courses currently enrolled in:
			</h5>
			<table>
				{% for course in courses %}
					<tr>
						<td>
							<li></li>
						</td>
						<td>
							<strong>{{ course.name.title }}</strong>
						</td>
						<td>
							<strong>Duration: </strong>{{ course.duration }}
						</td>
						<td>
							<strong>Pre-requisite: </strong>{{ course.pre_requisite.title }}
						</td>
						<td>
							<strong>Vocational: </strong>{{ course.is_vocational }}
						</td>
					</tr>
				{% endfor %}
			</table>
		{% endif %}
	</div>

	<div class="m-3">
		<h5>
			<p>
				Course you can enroll in:
			</p>
		</h5>

		<form method="POST">
			{% csrf_token %}
			<table>
				{{ form.as_table }}
				<tr>
					<td>
						<input class="btn btn-dark" type="submit" name="Login" value="Apply">
					</td>
				</tr>
			</table>
		</form>
	</div>

{% endblock %}

user_profile/templates/user_profile/course_details.html
{% extends 'user_profile/navbar.html' %}

{% block head %}
{% endblock %}

{% block title %}
	Courses
{% endblock %}


{% block content %}

	<form>
		{{ form }}
	</form>

	{% if messages %}
		<ul class="messages">
	    	{% for message in messages %}
	    		<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
	    	{% endfor %}
		</ul>
	{% endif %}

	<div class="m-3 course">
		{% if course %}
			<h5>
				{{ course.name.title }}
			</h5>
			<ul>
				<li>
					<strong>Duration: </strong> {{ course.duration }}
				</li>
				<li>
					<strong>Pre-requisite: </strong> {{ course.pre_requisite.title }}
				</li>
				{% if course.is_vocational %}
					<li>
						<strong>Course Type: </strong>Vocational
					</li>
				{% else %}
					<li>
						<strong>Course Type: </strong>Degree
					</li>
				{% endif %}
				<li>
					<strong>
						Subjects:
					</strong>
					<table class="table">
						<thead>
							<tr>
									<th scope="col">#</th>
									<th scope="col">Subject</th>
									<th scope="col">Teacher</th>
							</tr>
						</thead>
						<tbody>
							<ol>
								{% for subject in course.subjects.all %}
								    <tr>
								     	<th><li></li></th>
								     	<td>{{ subject.name.title }}</td>
								     	<td>{{ subject.teacher.user_profile.user.first_name.title }} {{ subject.teacher.user_profile.user.last_name.title }}</td>
								    </tr>
								{% endfor %}
							</ol>
						</tbody>
					</table>
							
				</li>
				<li>
					<a href="{% url 'user_profile:course_students' course.id %}">
						<strong>
							Students
						</strong>
					</a>
					enrolled in this course.
				</li>
			</ul>
		{% endif %}
		<a href="{% url 'user_profile:courses' %}">
			<button class="btn btn-light">
				Back to courses
			</button>
		</a>
	</div>

{% endblock %}

user_profile/templates/user_profile/courses.html
{% extends 'user_profile/navbar.html' %}

{% block head %}
	{% load static %}
            <script type="text/javascript" src="{% static 'user_profile/js/button.js' %}"></script>
{% endblock %}

{% block title %}
	Courses
{% endblock %}


{% block content %}

	{% if messages %}
		<ul class="messages">
	    	{% for message in messages %}
	    		<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
	    	{% endfor %}
		</ul>
	{% endif %}

	<div class="m-3 course">
		{% if courses %}
			<h3>
				Courses currently available:
			</h3>
			<table>
				{% for course in courses %}
					<tr>
						<td>
							<li></li>
						</td>
						<td>
							<a href="{% url 'user_profile:course_details' course.id %}">
								<strong>{{ course.name.title }}</strong>
							</a>
						</td>
						<td>
							<button class="btn btn-danger" id='{{ course.id }}' name="delete_course">
								Delete
							</button>
							
						</td>
					</tr>
				{% endfor %}
			</table>
		{% endif %}
	</div>

	<div class="m-3">
		<h3>
			Add courses:
		</h3>
		<form method="POST">
			{% csrf_token %}
			<table>
				{{ form.as_table }}
				<tr>
					<td>
						<input type="submit" name="Add_Course" value="Add Course">
					</td>
				</tr>
			</table>
		</form>
	</div>

{% endblock %}

user_profile/templates/user_profile/dashboard.html
{% extends 'user_profile/navbar.html' %}

{% block title %}
	Dashboard
{% endblock %}

{% block head %}
	{% load static %}
	<script type="text/javascript" src="{% static 'user_profile/js/api.js' %}"></script>
{% endblock %}


{% block content %}

	{% if messages %}
		<ul class="messages">
    		{% for message in messages %}
    			<li {% if message.tags %} class="{{ message.tags }}"{% endif %}>
    				{{ message }}
    			</li>
    		{% endfor %}
		</ul>
	{% endif %}

	<div class="m-3">
		<form method="POST">
			{% csrf_token %}
			<table>
				{{ form.as_table }}
				<tr>
					<td>
						<input class="btn btn-dark" type="submit" name="user_profile" value="Update">
					</td>
				</tr>
			</table>
		</form>
	</div>
	
	{% if studentform %}
		<div class="m-3">
			<form method="POST">
				{% csrf_token %}
				<table>
					{{ studentform.as_table }}
					<tr>
						<td>
							<input class="btn btn-dark" type="submit" name="student" value="Update">
						</td>
					</tr>
				</table>
			</form>
		</div>
	{% endif %}

	<a href="{% url 'user_profile:change_password' %}">
		<button>
			Change Password
		</button>
	</a>

{% endblock %}

user_profile/templates/user_profile/navbar.html
{% extends 'user_profile/base.html' %}

{% block navbar %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <strong class="navbar-brand" href="#">
            Welcome, {{ request.user.first_name.title }} {{ request.user.last_name.title }}
        </strong>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'user_profile:dashboard' %}">Dashboard</a>
                </li>

                {% if request.user.userprofile.user_type == "teacher" %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user_profile:courses'%}">Courses</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user_profile:subjects' %}">Subjects</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user_profile:students' %}">Students</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user_profile:course_apply'%}">Courses</a>
                    </li>
                {% endif %}
            </ul>
        </div>
        <div class="d-flex justify-content-start">
                <li class="nav-item ">
                    <a class="nav-link" href="{% url 'user_profile:sign_out' %}">Sign Out
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

{% endblock %}

user_profile/templates/user_profile/password_reset_confirm.html
{% extends 'user_profile/base.html' %}

{% block title %}
	Reset Password
{% endblock %}


{% block content %}

	{% if messages %}
		<ul class="messages">
    		{% for message in messages %}
    			<li {% if message.tags %} class="{{ message.tags }}"{% endif %}>
    				{{ message }}
    			</li>
    		{% endfor %}
		</ul>
	{% endif %}
	<h3>
		Reset password:
	</h3>
	<p>
		Set your new password.
	</p>
	<form method="post">
		{% csrf_token %}
		<table>
			{{ form.as_table }}
		</table>
		<button type="submit">Reset my password</button>
	</form>

{% endblock %}

user_profile/templates/user_profile/reset_password_done.html
{% extends 'user_profile/base.html' %}

{% block title %}
	Reset Password
{% endblock %}


{% block content %}

	<h3>
		Reset password mail successfully sent:
	</h3>
	<p>
		A email with the details on how to reset your password is sent to you. Please check your email and follow the instruction on how to reset your password.
	</p>
		<a href="{% url 'user_profile:sign_in' %}">
			<button type="submit">
				Sign In
			</button>
		</a>

{% endblock %}

user_profile/templates/user_profile/search_results.html
{% for student in students %}
	<tr class="student_data">
		<th scope="row">
			<li></li>
		</th>
		<td>
			{{ student.user_profile.user.first_name.title }} {{ student.user_profile.user.last_name.title }}
		</td>
		<td>
			{{ student.qualification.title }}
		</td>
		<td>
			{{ student.start_year }}
		</td>
		<td>
			{% for course in student.courses.all %}
				<li>
					{{ course }}
				</li>
			{% endfor %}
		</td>
	</tr>
{% endfor %}

user_profile/templates/user_profile/sign_in.html
{% extends 'user_profile/base.html' %}

{% block title %}
Sign In
{% endblock %}


{% block content %}

	{% if messages %}
		<ul class="messages">
    		{% for message in messages %}
    		<li {% if message.tags %} class="{{ message.tags }}"{% endif %}>
    			{{ message }}
    		</li>
    		{% endfor %}
		</ul>
	{% endif %}
	<div class="m-3">
		<form method="POST">
			{% csrf_token %}
			<table>
				{{ form.as_table }}
				<tr>
					<td></td>
					<td>
						<input class="btn btn-dark" type="submit" name="Sign_In" value="Sign In">
						<sup>
						&emsp;	<a href="{% url 'user_profile:password_reset' %}">Forgot password?</a>
						</sup>
					</td>
				</tr>
			</table>
		</form>
		<a href="{% url 'user_profile:sign_up' %}">
			<button> Sign Up </button>
		</a>
	</div>

{% endblock %}

user_profile/templates/user_profile/sign_up.html
{% extends 'user_profile/base.html' %}

{% block title %}
Sign Up
{% endblock %}


{% block content %}

<div class="container-fluid mt-3">
	<form method="POST">
		{% csrf_token %}
		<table>
			{{ form.as_table }}
			<tr>
				<td>
					
				</td>
				<td>
					<input type="submit" class="btn btn-dark" name="sign_up" value="Sign Up">
				</td>
			</tr>
		</table>
	</form>
	<a href="{% url 'user_profile:sign_in' %}">
		<button class="btn btn-info">Sign In</button>
	</a>
</div>

{% endblock %}

user_profile/templates/user_profile/students.html
{% extends 'user_profile/navbar.html' %}

{% block head %}
{% endblock %}
{% block title %}
	Students
{% endblock %}


{% block content %}
	
	{% if messages %}
		<ul class="messages">
    		{% for message in messages %}
    		<li {% if message.tags %} class="{{ message.tags }}"{% endif %}>
    			{{ message }}
    		</li>
    		{% endfor %}
		</ul>
	{% endif %}

	<div class="m-3 course">
		{% if students %}
			<div class="container">
				<div class="row">
					<div class="col-sm">
						<h3>
							Students list:
						</h3>
					</div>
					<div class="col-sm input-group">
						{% if course_id %}
							<form action="{% url 'user_profile:course_students' course_id %}" method="GET">
								{{ form }}
								<button type="submit" class="btn btn-primary">
									Go
								</button>
							</form>
						{% else %}
							<form action="/students/" method="GET">
								{{ form }}
								<button type="submit" class="btn btn-primary">
									Go
								</button>
							</form>
						{% endif %}
					</div>
				</div>
			</div>
			<table class="table">
				<thead>
					<tr>
						<th scope="col">#</th>
						<th scope="col">Name</th>
						<th scope="col">Qualification</th>
						<th scope="col">Start Year</th>
						<th scope="col">Courses</th>
					</tr>
				</thead>
				<tbody>
					<ol class="student_list">
						{% for student in students %}
							<tr class="student_data" id={{ student.id }}>
								<th scope="row">
									<li></li>
								</th>
								<td>
									{{ student.user_profile.user.first_name.title }} {{ student.user_profile.user.last_name.title }}
								</td>
								<td>
									{{ student.qualification.title }}
								</td>
								<td>
									{{ student.start_year }}
								</td>
								<td>
									{% for course in student.courses.all %}
										{% if course_id %}
											{% if course_id == course.id %}
												<li>
													<strong>
														{{ course }}
													</strong>
													
												</li>
											{% else %}
												<li>
													{{ course }}
												</li>
											{% endif %}
										{% else %}
											<li>
												{{ course }}
											</li>
										{% endif %}
									{% endfor %}
								</td>
							</tr>
						{% endfor %}
					</ol>
				</tbody>
			</table>
		{% else %}
			<h3>
				<strong>
					No Student enrolled yet:
				</strong>
			</h3>
		{% endif %}
	</div>
{% endblock %}